// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:nextoffice/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEVtwidTOSSx5XjYEteDDSDKAHfwCz-WQ',
    appId: '1:96573718732:web:a32e6daf86bd8905028269',
    messagingSenderId: '96573718732',
    projectId: 'nextoffice-4a398',
    authDomain: 'nextoffice-4a398.firebaseapp.com',
    storageBucket: 'nextoffice-4a398.firebasestorage.app',
    measurementId: 'G-28XRZJZES4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGvzqffGmUsfAuITlr3lXynZxVm2ZEgws',
    appId: '1:96573718732:android:afdf43ca2697312f028269',
    messagingSenderId: '96573718732',
    projectId: 'nextoffice-4a398',
    storageBucket: 'nextoffice-4a398.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzFuAOLgLt2_d_xMC7iwxEeEyyO_H6Rwg',
    appId: '1:96573718732:ios:78ce0577471a766e028269',
    messagingSenderId: '96573718732',
    projectId: 'nextoffice-4a398',
    storageBucket: 'nextoffice-4a398.firebasestorage.app',
    iosBundleId: 'com.nextoffice.app.stg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzFuAOLgLt2_d_xMC7iwxEeEyyO_H6Rwg',
    appId: '1:96573718732:ios:867fdf0c2be1fc8e028269',
    messagingSenderId: '96573718732',
    projectId: 'nextoffice-4a398',
    storageBucket: 'nextoffice-4a398.firebasestorage.app',
    iosBundleId: 'com.nextoffice.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEVtwidTOSSx5XjYEteDDSDKAHfwCz-WQ',
    appId: '1:96573718732:web:81fbdb74847dfcd9028269',
    messagingSenderId: '96573718732',
    projectId: 'nextoffice-4a398',
    authDomain: 'nextoffice-4a398.firebaseapp.com',
    storageBucket: 'nextoffice-4a398.firebasestorage.app',
    measurementId: 'G-ZPFTZDVB4K',
  );

}